name: Build Docker Image

on:
    workflow_call:
        inputs:
            ref:
                required: true
                type: string
            base:
                required: true
                type: string
            tag:
                required: true
                type: string

jobs:
    docker:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ inputs.ref }}

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Login to Docker Hub
              uses: docker/login-action@v2
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push
              uses: docker/build-push-action@v3
              with:
                  push: true
                  tags: xowap/trafficserver:${{ inputs.tag }}
                  build-args:
                      BASE_IMAGE: ${{ inputs.base }}
