name: Release

on:
    workflow_dispatch:

jobs:
    build-image-default:
        uses: ./.github/workflows/build-image.yml
        with:
            ref: ${{ github.ref }}
            base: default
            tag: latest
            docker_username: ${{ secrets.DOCKER_USERNAME }}
            docker_token: ${{ secrets.DOCKER_TOKEN }}
        secrets: inherit

    build-image-no-hwloc:
        uses: ./.github/workflows/build-image.yml
        with:
            ref: ${{ github.ref }}
            base: no-hwloc
            tag: no-hwloc
            docker_username: ${{ secrets.DOCKER_USERNAME }}
            docker_token: ${{ secrets.DOCKER_TOKEN }}
        secrets: inherit
