name: Release

on:
    workflow_dispatch:

jobs:
    build-image-default:
        uses: ./.github/workflows/build-image.yml
        with:
            ref: ${{ github.ref }}
            base: default
            tag: latest
        secrets:
            inherit: true

    build-image-no-hwloc:
        uses: ./.github/workflows/build-image.yml
        with:
            ref: ${{ github.ref }}
            base: no-hwloc
            tag: no-hwloc
        secrets:
            inherit: true
